#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0.35 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    touchpad {
        natural_scroll = true
        scroll_factor = 0.4
    }
}

# https://wiki.hypr.land/Configuring/Gestures/
gesture = 3, horizontal, workspace
gesture = 3, vertical, dispatcher, togglespecialworkspace, Z

# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
